### ISSUE TITLE
NameError: name 'stripper' is not defined

### ISSUE THREAD

**Issue by clwgg** [sulami/feed2maildir#3]
Hi,
the tool runs great without any options, but when I use `feed2maildir -s`, I get the following error message:

```
Traceback (most recent call last):
  File "/usr/bin/feed2maildir", line 49, in <module>
    main()
  File "/usr/bin/feed2maildir", line 46, in main
    converter.run()
  File "/usr/lib/python3.7/site-packages/feed2maildir/converter.py", line 99, in run
    self.write(self.compose(newfeed, newpost))
  File "/usr/lib/python3.7/site-packages/feed2maildir/converter.py", line 192, in compose
    desc = stripper.get_data()
NameError: name 'stripper' is not defined
```
I'm using the following versions:
```
feed2maildir           0.3.6             
feedparser             5.2.1             
python-dateutil        2.8.0             
Python 3.7.4
```
Any help would be appreciated.

**Comment by sulami** [comment]
Hi @clwgg,

I had a quick look and pushed a new version, 0.3.7, let me know if your issue persists.

**Comment by clwgg** [comment]
awesome, it's working! thanks a lot for the quick fix.
